/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yukitoohira' at '16/11/16 17:38' with Gradle 3.2
 *
 * @author yukitoohira, @date 16/11/16 17:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
